---
- name: Preparation steps to for all nodes of a kubernetes cluster
  hosts: all
  become: true
  tasks:
  - name: Set hostname
    hostname:
        name: "{{ new_hostname }}"
        use: systemd

  - name: APT HTTPS Transport
    apt:
        name: apt-transport-https
        state: present

  - name: Ansible Update Cache and Upgrade all Packages
    apt:
        name: "*"
        state: latest
        update_cache: yes

  - name: Install packages
    apt:
        name:
        - tmux
        - emacs
        - net-tools
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - gnupg-agent
        - lsb-release
        - software-properties-common
        state: present
        update_cache: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Update Apt Cache after Docker repo addition
    apt:
        update_cache: yes

  - name: Install Docker
    apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

  - name: Install Kubernetes
    apt:
        name:
        - kubelet
        - kubeadm
        - kubectl

  - name: Remove containerd default config
    file:
        path: /etc/containerd/config.toml
        state: absent

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}

  - name: Restart containerd service
    systemd:
        name: containerd
        state: restarted

  - name: Restart kubelet
    systemd:
        name: kubelet
        state: restarted
