---
- name: Preparation steps to for all nodes of a kubernetes cluster
  hosts: all
  become: true
  tasks:
  - name: Set hostname
    hostname:
        name: "{{ new_hostname }}"
        use: systemd

  - name: APT HTTPS Transport
    apt:
        name: apt-transport-https
        state: present

  - name: Ansible Update Cache and Upgrade all Packages
    apt:
        name: "*"
        state: latest
        update_cache: yes

  - name: Install packages
    apt:
        name:
        - tmux
        - emacs
        - net-tools
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        state: present
        update_cache: yes

  - name: Add docker APT repo key to keyring
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Add Kubernetes APT repo key to keyring
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  - name: Add new Docker apt repo to apt sources
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Add new Kubernetes apt repo to apt sources
    shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - name: Update Apt Cache after Docker repo addition
    apt:
        update_cache: yes

  - name: Install Docker
    apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

  - name: Install Kubernetes
    apt:
        name:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni

  - name: Remove containerd default config
    file:
        path: /etc/containerd/config.toml
        state: absent

  - name: Restart containerd service
    systemd:
        name: containerd
        state: restarted