---
- name: Get Join from Controller
  hosts: controller
  become: true
  gather_facts: false
  tasks:
  - name: Get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - debug:
        msg: "What is the join command? {{ join_command_raw }}"

  - name: Set join command
    set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Run Join on worker nodes
  hosts: workers
  become: true
  tasks:
  - name: Remove swap
    shell: swapoff -a

  - name: Join Cluster
    shell: "{{ hostvars['k8_joshua_test_primary'].join_command }} >> node_joined.txt"
    args:
        chdir: $HOME
        creates: node_joined.txt