---
- name: Preparation steps to for all nodes of a kubernetes cluster
  hosts: kubernetes
  tasks:
  - name: Ansible Update Cache and Upgrade all Packages
    become: true
    apt:
        name: "*"
        state: latest
        update_cache: yes

  - name: Install packages
    become: true
    apt:
     name:
      - tmux
      - emacs
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
     force_apt_get: yes
     update_cache: yes

  - name: Add docker APT repo key to keyring
    become: true
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  - name: Add new Docker apt repo to apt sources
    become: true
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

